name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      # Listar archivos después del checkout para verificar contenido
      - name: List files in the workspace
        run: ls -la

      # Instalación de Node.js y dependencias
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Listar archivos en el directorio src/entities para verificar que existan
      - name: List files in src/entities
        run: ls -la ./src/entities

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/talent-place-image:latest
